### ISSUE TITLE
textbox: username

### ISSUE THREAD

**Issue by coindup** [fmiboy/steemit#1]
I noticed that when I'm typing in my username there seems to be some kinda script running that is trying to find a name...it makes it hard to type my username which is pseudo and not a word as in auto-correct

**Comment by fmiboy** [comment]
Thanks @coindup 
Can you clarify this?
Are you typing your username on Search page or Login page? In login page you can use only your username and leave password empty as it is not required yet. Search page, currently starts to search after 3 characters, 4th and forward characters when typed app searches blockchain to show relevant info.

**Comment by fmiboy** [comment]
This is fixed on upcoming beta 0.0.4
